apiVersion: v1
kind: Service
metadata:
  name: voyage-api-service
spec:
  type: LoadBalancer  # Exposes the service to your local machine
  selector:
    app: voyage-api
  ports:
    - protocol: TCP
      port: 5000      # Port accessible on your computer
      targetPort: 5000 # Port the container is listening on
